// +build !ignore_autogenerated

//
// Copyright (c) 2019, VSHN AG, info@vshn.ch
// Licensed under "BSD 3-Clause". See LICENSE file.
//
//

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/vshn/cdays-namespace-poc/pkg/apis/control/v1alpha1.ManagedNamespace":       schema_pkg_apis_control_v1alpha1_ManagedNamespace(ref),
		"github.com/vshn/cdays-namespace-poc/pkg/apis/control/v1alpha1.ManagedNamespaceSpec":   schema_pkg_apis_control_v1alpha1_ManagedNamespaceSpec(ref),
		"github.com/vshn/cdays-namespace-poc/pkg/apis/control/v1alpha1.ManagedNamespaceStatus": schema_pkg_apis_control_v1alpha1_ManagedNamespaceStatus(ref),
	}
}

func schema_pkg_apis_control_v1alpha1_ManagedNamespace(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ManagedNamespace is the Schema for the managednamespaces API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/vshn/cdays-namespace-poc/pkg/apis/control/v1alpha1.ManagedNamespaceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/vshn/cdays-namespace-poc/pkg/apis/control/v1alpha1.ManagedNamespaceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/vshn/cdays-namespace-poc/pkg/apis/control/v1alpha1.ManagedNamespaceSpec", "github.com/vshn/cdays-namespace-poc/pkg/apis/control/v1alpha1.ManagedNamespaceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_control_v1alpha1_ManagedNamespaceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ManagedNamespaceSpec defines the desired state of ManagedNamespace",
				Properties: map[string]spec.Schema{
					"description": {
						SchemaProps: spec.SchemaProps{
							Description: "Description may show further (human readable) information",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_control_v1alpha1_ManagedNamespaceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ManagedNamespaceStatus defines the observed state of ManagedNamespace",
				Properties: map[string]spec.Schema{
					"createdNamespace": {
						SchemaProps: spec.SchemaProps{
							Description: "CreatedNamespace references the UID of the created namespace object",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"phase": {
						SchemaProps: spec.SchemaProps{
							Description: "Phase is the current lifecycle phase of the ManagedNamespace.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}
