apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managednamespaces.control.appuio.ch
spec:
  group: control.appuio.ch
  names:
    kind: ManagedNamespace
    listKind: ManagedNamespaceList
    plural: managednamespaces
    singular: managednamespace
    shortNames:
    - mns
  additionalPrinterColumns:
  - name: Description
    type: string
    description: The description of the ManagedNamespace
    JSONPath: .spec.description
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              description: Description may show further (human readable) information
              type: string
          type: object
        status:
          properties:
            createdNamespace:
              description: CreatedNamespace references the UID of the created namespace
                object
              type: string
            phase:
              description: Phase is the current lifecycle phase of the ManagedNamespace.
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
