apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cdays-namespace-poc
rules:
- apiGroups:
  - ""
  resources:
  - namespace
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - control.appuio.ch
  resources:
  - '*'
  verbs:
  - '*'
